### PR TITLE
Fix use of ` in formatting in README

### PR DESCRIPTION
**Pull request by mitchhentges**

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Thanks. :)

**Comment by mattrobenolt** [comment]
Oh, haha, this is wrong too. It's rst, not markdown. I'll fix.

**Comment by mitchhentges** [comment]
Oh my haha.
Sorry about that! It looks funny in GitHub :wink:

**Comment by mattrobenolt** [comment]
Fixed it for good with https://github.com/getsentry/sentry-auth-github/commit/2047d3833bbeedb8720b59de551daa61691f6c93

**Pull request merged**
